# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml
# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
linter:
  rules:
    omit_local_variable_types: false,
    prefer_single_quotes: false,
    non_constant_identifier_names: false.
#     - camel_case_types
analyzer:
#   exclude:
#     - path/to/excluded/files/**