arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: l10n.dart
output-class: SL
synthetic-package: false
output-dir: lib/generated
preferred-supported-locales: en
nullable-getter: false
